Service JSON
vtex-apps/checkout-graphql pull request #110
Opened 2020-12-08 16:44 UTC by tlgimenes

#### What problem is this solving?
There is only one single instance of checkout-graphql in our admin-* cluster. This PR adds a min replicas of 2 so we never have a single pod instance.

Having one single pod instance caused marin to go down after a pod instance went sick. This should prevent further problems

#### How should this be manually tested?

[Workspace](url)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Jira story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

2020-12-08 16:45 UTC, lucasecdb approved these changes
changelog?

2020-12-08 18:03 UTC, wdsrocha requested changes
lgtm, but as Lucas asked, could you update the changelog please?

2020-12-09 18:40 UTC, lucasecdb approved these changes

2020-12-09 21:58 UTC, wdsrocha submitted a review, later dismissed

2020-12-14 18:23 UTC, lucasecdb approved these changes

2020-12-14 18:25 UTC, merged