fix: we  keep client information in orderform even when the user is logged out
vtex-apps/checkout-graphql pull request #192
Opened 2023-12-07 19:52 UTC by iago1501

#### What problem is this solving?

When user is logged out, we keep the information in order form with the user identified. Currently, we have a bug that when the client logs with a different user, we don't change the previous user details in order form, but, should we keep the orderFormProfile in orderForm even after the user is logged out?

#### How should this be manually tested?

- Log in with a user
- Check your data at checkout
- Logout
- Check again in checkout and your client profile should be empty

[Workspace](https://iespinoza2--storecomponents.myvtex.com/)

#### Checklist/Reminders

- [ ] Updated `README.md`.
- [ ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Jira story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

2024-01-17 18:57 UTC, jeffersontuc commented
Hi @iago1501 
I linked those changes in a workspace on the `checkoutio` account. And it looks like there's something weird. Basically, I can't proceed from the identification step. Maybe, after these changes, we are cleaning `clientProfileData` info that shouldn't be touched.

Besides that, I think it's worthy to test these changes for the first purchase scenario, when the user doesn't have a proper profile. In this case, do we still want to clean up de clientProfileData on every `orderForm` query call?

2024-01-18 20:25 UTC, rbussola commented
Workspace com as atualizações: https://logout--checkoutio.myvtex.com/
Testes:
- Comprador logado ✅
- Comprador não logado sem perfil completo ✅
- Comprador não logado com perfil completo ✅
- Ao deslogar, orderForm sem profileData e shippingData ✅

2024-02-19 12:37 UTC, vmarcosp requested changes

2024-02-19 12:37 UTC, vmarcosp commented on node/clients/checkout.ts
> +        if (!err.response || /^3..$/.test((err as AxiosError).code ?? '')) {
Sugestão pra não usarmos regex + explicitar um pouco mais a lógica (assim rola até remover o comentário):
```suggestion
        const canWeIgnoreError = err instanceof AxiosError && err.code >= 300 && err.code < 400
        if (!err.response || canWeIgnoreErrorCode) {
```

Outra opção também é usar o `validateStatus` do axios ao fazer o `this.get(...)`, dessa forma podemos checar se é um `3xx` e não lançar o erro:
https://axios-http.com/docs/handling_errors

Algo como isso:
![Screenshot 2024-02-19 at 09 36 41](https://github.com/vtex-apps/checkout-graphql/assets/20327229/ed840033-c2aa-453b-8573-4b92192feb25)
Mas alterando pra esse case: 
```
{ validateStatus: (status) => status >= 400 }
```
Faz sentido essas opções?

2024-02-19 14:28 UTC, closed without merging