Feat/pickup options
vtex-apps/checkout-graphql pull request #98
Opened 2020-10-05 13:28 UTC by leoWorkingGood

#### What problem is this solving?

- Recieve in type Shipping the pickup options (pickupOptions)
- Mutation to allow to select a pickup point of a product in the product page

#### How should this be manually tested?

Here it is a print from graphql-ide showing the mutation working, and the pickupOptions type showing all the pickup pointer available    https://prnt.sc/
The mutation from print: [Link](https://vtexpr--iocea.myvtex.com/_v/private/vtex.checkout-graphql@0.42.0/graphiql/v1?operationName=pick&query=mutation%20pick(%24id%3A%20ID%2C%20%24pickID%3A%20String)%20%7B%0A%20%20selectPickupOption(orderFormId%3A%20%24id%2C%20pickupOptionId%3A%20%24pickID)%20%7B%0A%20%20%20%20id%0A%20%20%20%20shipping%20%7B%0A%20%20%20%20%20%20pickupOptions%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20price%0A%20%20%20%20%20%20%20%20isSelected%0A%20%20%20%20%20%20%20%20friendlyName%0A%09%09%09%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22id%22%3A%20%221321189263234cff8f4848dcc1c7b6ec%22%2C%0A%20%20%22pickID%22%3A%20%22Retirada%20na%20Loja%20(SMO)%22%0A%7D)

The product used [prod](https://vtexpr--iocea.myvtex.com/blusa-feminina-basica-texturizada-manga-bufante-decote-redondo-preta-9856461-preto/p)

SKU of itens: 2676332 and 2676333

#### Checklist/Reminders

- [*] Updated `README.md`.
- [*] Updated `CHANGELOG.md`.
- [*] Linked this PR to a Jira story (if applicable).
- [*] Updated/created tests (important for bug fixes).
- [*] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️ | New feature 
_ | Breaking change 
_ | Technical improvements 

#### Notes

Lucas Cordeiro and Bruno Moreira are directly helping in this MR approval

2020-10-05 18:08 UTC, lucasecdb submitted a review, later dismissed

2020-10-05 20:53 UTC, darlenedms commented on node/constants/index.ts
> +export const PICKUP_IN_STORE = 'pickup-in-point'
I would suggest to change the const name too.
```suggestion
export const PICKUP_IN_POINT = 'pickup-in-point'
```

2020-10-05 21:03 UTC, darlenedms requested changes
Just rename the const name and you are good to go. 😄

2020-10-06 11:49 UTC, leoWorkingGood commented
@darlenedms updated =)

2020-10-06 12:45 UTC, lucasecdb commented
@leoWorkingGood you'll need to update it in all the files that use this constant

2020-10-06 13:32 UTC, leoWorkingGood commented
@lucasecdb All the files were updated with the new constant name

2020-10-06 14:31 UTC, lucasecdb approved these changes

2020-10-06 17:22 UTC, darlenedms approved these changes
🚚

2020-10-06 17:41 UTC, merged